# Generated by Django 6.1 on 2026-08-23 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(help_text='Stores string, integer, or JSON dynamic configurations')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General Configuration & Branding'), ('ATTENDANCE', 'Attendance, Grace Periods & Shifts'), ('PAYROLL', 'Payroll Formulas, Rules & Multipliers'), ('SECURITY', 'Security, Session Timeouts & Allowed Domains'), ('BIOMETRICS', 'Biometric Import Profiles & Hardware Mappings')], default='GENERAL', max_length=50)),
            ],
            options={
                'db_table': 'system_parameters',
                'ordering': ['category', 'key'],
            },
        ),
    ]
