# Generated by Django 5.0.6 on 2026-08-27 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(db_index=True, help_text="Unique slug/key e.g. 'dashboard', 'user-management'", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable module/page title', max_length=150)),
                ('module', models.CharField(help_text="Category grouping e.g. 'SYSTEM', 'HR', 'ATTENDANCE', 'PAYROLL', 'SELF_SERVICE'", max_length=100)),
                ('icon', models.CharField(default='fi fi-rr-apps', help_text='Flaticon / CSS icon class', max_length=100)),
                ('path', models.CharField(blank=True, help_text="Frontend route path e.g. '/dashboard'", max_length=150, null=True)),
                ('tag', models.CharField(blank=True, help_text="Optional UI pill tag e.g. 'Security', 'PHP'", max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Pinned or primary highlighted item')),
                ('display_order', models.IntegerField(default=0, help_text='Sequence index for sidebar navigation')),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text="List of permitted CRUD actions e.g. ['view', 'add', 'edit', 'delete']")),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings_module_access',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
