from prisma import Prisma

# The Prisma client is auto-generated by the Prisma CLI (run `prisma generate` once your schema is set up)
prisma = Prisma()

async def get_db():
    """
    FastAPI dependency yielding the connected Prisma client instance.
    """
    if not prisma.is_connected():
        await prisma.connect()
    try:
        yield prisma
    finally:
        # Prisma connection handles pooling internally; keep connected during requests.
        pass
